SUCCESS = 0

ROOM_NOT_FOUND = 4
ROOM_EXISTS = 3
ROOM_REGISTRY_FULL = 7

INVALID_ROOMNAME = 10
INVALID_USERNAME = 9
INVALID_PASSWORD = 11

USER_NOT_FOUND = 1
USER_EXISTS = 2
USER_REGISTRY_FULL = 8
WRONG_PASSWORD = 5
USER_SESSION_ERROR = 6

RECIPIENT_NOT_FOUND = 12